lastupdatecheck: 0
recentrepos:
- /Users/alchemist/code/adtec-extractor
- /Users/alchemist/dotfiles
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
